### ISSUE TITLE
Zippy bitReverseTable error

### ISSUE THREAD

**Issue by richrumble** [HuskyHacks/ShadowSteal#1] opened 2021-07-21 14:15 UTC
Tried compiling inside ubuntu on win10, had lots of proxy issues with Nim, so I tried locally installing zippy, looks like it worked.
However when compiling I do get a zippy error, and I've tried a few versions of Zippy just to see. It's probably a bug zippy needs to fix, but I wanted to see if you had any other suggestions as well :) I've tried specifying other CPU types, and no CPU with the same results....
/mnt/c/Temp/ShadowSteal-main/src$ nim c --d:mingw --cpu=i386 --app=console ShadowSteal.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: ShadowSteal [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: unicode [Processing]
Hint: pathnorm [Processing]
Hint: osseps [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: time_t [Processing]
Hint: osproc [Processing]
Hint: strtabs [Processing]
Hint: hashes [Processing]
Hint: streams [Processing]
Hint: cpuinfo [Processing]
Hint: ziparchives [Processing]
Hint: tables [Processing]
Hint: zippy [Processing]
Hint: common [Processing]
Hint: zippyerror [Processing]
/home/xxxxxx/.nimble/pkgs/zippy-0.6.0/zippy/common.nim(137, 13) Error: type mismatch: got <int literal(16), uint8>
but expected one of:
proc `-`(x, y: int64): int64
  first type mismatch at position: 2
  required type for y: int64
  but expression 'length' is of type: uint8
 
Any other ideas?

**Comment by richrumble** [comment] 2021-07-21 14:23
nim c --d:mingw --cpu=amd64 --app=console ShadowSteal.nim
same error btw

**Comment by HuskyHacks** [comment] 2021-07-21 15:06
Hi! Thanks for opening the issue. I've seen this and will examine after work today when I have some off time. Initial thoughts is that WSL be crazy and things that work perfectly fine on regular Ubuntu can be tricky to troubleshoot in the subsystem. Will take a look later today, for now I'd recommend spinning up a Kali/Ubuntu Desktop VM and try it that way.

**Comment by HuskyHacks** [comment] 2021-07-21 23:18
@richrumble I did take a look at this but was unable to reproduce it with my own build. I'm pretty sure this is either a bug with WSL or a bug in zippy. In either case, I don't think I can do much to help. Closing for now but I will try again over the next few days.

**Closed as completed by HuskyHacks** 2021-07-21 23:18 UTC
